apiVersion: v1
entries:
  memphis:
  - apiVersion: v2
    appVersion: 0.4.3
    created: "2022-04-11T15:50:54.605102+03:00"
    description: Memphis.dev Helm chart
    digest: f557dcaf1fbf21fe2fd5ae7ee28a1a5a3c149c9e78c1a16ebdcb9bd5cf9117e5
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    name: memphis
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-0.4.3.tgz
    version: 0.4.3
  - apiVersion: v2
    appVersion: 0.4.2
    created: "2023-01-05T16:52:20.459753338Z"
    description: Memphis.dev Helm chart
    digest: 3a17890606d0eb961f17a88fc5a9d2258d2071745ba21d8864946a50ed7e3ebb
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    name: memphis
    type: application
    urls:
    - memphis-0.4.2.tgz
    version: 0.4.2
  - apiVersion: v2
    appVersion: 0.4.1
    created: "2023-01-05T16:52:20.458407599Z"
    description: Memphis.dev Helm chart
    digest: 3901e5059d04a93f2afef1e66f0f097610c4cf41ec8f85e030c3b4749a0b1c9b
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    name: memphis
    type: application
    urls:
    - memphis-0.4.1.tgz
    version: 0.4.1
  - apiVersion: v2
    appVersion: 0.4.0
    created: "2023-01-05T16:52:20.456989807Z"
    description: Memphis.dev Helm chart
    digest: abe8ef969af061633e0566bcc6f764a6175d74fe378d183a79394a3c4cf99b6b
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    name: memphis
    type: application
    urls:
    - memphis-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v2
    appVersion: 0.3.6
    created: "2023-01-05T16:52:20.455588267Z"
    description: Memphis.dev Helm chart
    digest: 1463b0842ae745cfbc39bbbd59bf4aed1829610eb3305a5c9f0e8671fb9b433e
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    name: memphis
    type: application
    urls:
    - memphis-0.3.6.tgz
    version: 0.3.6
  - apiVersion: v2
    appVersion: 0.3.5
    created: "2023-01-05T16:52:20.454188229Z"
    description: Memphis.dev Helm chart
    digest: 9e05f5310f8456c431041b4e44f3570e4ae7d3bdab27d58f64c2486483951a2c
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    name: memphis
    type: application
    urls:
    - memphis-0.3.5.tgz
    version: 0.3.5
  - apiVersion: v2
    appVersion: 0.3.0
    created: "2023-01-05T16:52:20.452182208Z"
    description: A Helm chart for Kubernetes
    digest: df8bc3b91ffd995e9ee743c4814ce37b38ac55f9366d16a07eebf5f05a03d462
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    name: memphis
    type: application
    urls:
    - memphis-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: 0.2.2
    created: "2023-01-05T16:52:20.450737753Z"
    description: A Helm chart for Kubernetes
    digest: d28563593f1577bb2381da7ec7a2b1a06301b04f30202ef00627127e21606657
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    name: memphis
    type: application
    urls:
    - memphis-0.2.2.tgz
    version: 0.2.2
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-01-05T16:52:20.449391246Z"
    description: A Helm chart for Kubernetes
    digest: 28d3abb9dbc8bb4e5d98e319af96bee39d7079373bc6f3ea1459f057557f07a2
    name: memphis
    type: application
    urls:
    - memphis-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-01-05T16:52:20.448044406Z"
    description: A Helm chart for Kubernetes
    digest: 8a6ec6bc3d6cdaed00455814cceac7ee4096268d08e82bc9ca0af4cdf3a65cf1
    name: memphis
    type: application
    urls:
    - memphis-0.2.0.tgz
    version: 0.2.0
generated: "2023-01-05T16:52:20.44658575Z"
