{{- if not .Values.memphis.creds.secretConfig.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.memphis.creds.secretConfig.name }}
  namespace: {{ include "memphis.namespace" . }}
type: Opaque
data: {{- ( include "gen.memphis.secret" . ) | nindent 2 -}}
{{- end -}}
