apiVersion: v1
kind: Service
metadata:
  name: memphis-external
  namespace: memphis-do
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "9000"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert:  arn:aws:acm:us-east-1:221323242847:certificate/b593e269-ecdb-4a8a-a677-8ba57c0e6672
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  ports:
  - name: https
    port: 443
    targetPort: 9000
  - name: memphis-ws
    port: 7770
    targetPort: 7770 
  - name: memphis-cp-tcp
    port: 6666
    protocol: TCP
    targetPort: 6666
  selector:
    app.kubernetes.io/instance: memphis
    app.kubernetes.io/name: memphis
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: memphis-gw-external
  namespace: memphis-do
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:221323242847:certificate/5fb4de27-cb63-4081-a012-2d3514f78a8d
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "restgw"
spec:
  ports:
  - name: restgw
    port: 443
    protocol: TCP
    targetPort: 4444
  selector:
    app: memphis-rest-gateway
  type: LoadBalancer
